apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elasticsearch-backup
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: elasticsearch-backup
            image: your-backup-image:version
            env:
              - name: ELASTICSEARCH_URL
                value: http://elasticsearch:9200
          restartPolicy: OnFailure
